package hesync

import (
	"fmt"
	"sync"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
)

// DiskEvaluationKeySet implements the rlwe.EvaluationKeySet interface backed
// by disk storage with prefetching. Instead of keeping all EVKs in memory,
// keys are stored as individual files on disk and loaded on-demand according
// to a prefetch plan generated from a dry-run trace.
//
// This is the central component of HESync. It integrates with the existing
// Lattigo evaluator infrastructure transparently — the evaluator calls
// GetGaloisKey/GetRelinearizationKey as usual, and this implementation
// either returns an already-loaded key or blocks until the prefetcher
// delivers it from disk.
type DiskEvaluationKeySet struct {
	index      *EVKIndex
	prefetcher *Prefetcher
	plan       *Plan

	// step tracks the current position in the plan
	step int
	mu   sync.Mutex

	// galoisElsList caches the list of all known Galois elements
	galoisElsList []uint64
}

// NewDiskEvaluationKeySet creates a new disk-backed EvaluationKeySet.
//
// Parameters:
//   - index: maps key identifiers to file paths on disk
//   - plan: the prefetch plan generated by GeneratePlan
//   - workers: number of concurrent loader goroutines (0 for default=4)
func NewDiskEvaluationKeySet(index *EVKIndex, plan *Plan, workers int) *DiskEvaluationKeySet {
	prefetcher := NewPrefetcher(plan, index, workers)

	return &DiskEvaluationKeySet{
		index:         index,
		prefetcher:    prefetcher,
		plan:          plan,
		galoisElsList: index.GetGaloisElementsList(),
	}
}

// GetGaloisKey retrieves a GaloisKey for the given Galois element.
// If the key is already loaded (by the prefetcher), it returns immediately.
// Otherwise, it blocks until the prefetcher delivers the key, or loads
// it synchronously as a fallback.
//
// This method advances the plan step counter and executes the corresponding
// prefetch instructions.
func (d *DiskEvaluationKeySet) GetGaloisKey(galEl uint64) (*rlwe.GaloisKey, error) {
	d.mu.Lock()
	step := d.step
	d.step++
	d.mu.Unlock()

	// Execute prefetch instructions for this step
	d.prefetcher.ExecuteStep(step)

	// Try to get the key from the prefetcher
	if gk := d.prefetcher.GetGaloisKey(galEl); gk != nil {
		return gk, nil
	}

	// Fallback: synchronous load from disk
	path, ok := d.index.GaloisKeys[galEl]
	if !ok {
		return nil, fmt.Errorf("GaloisKey[%d] not found in index", galEl)
	}

	gk, err := LoadGaloisKey(path)
	if err != nil {
		return nil, fmt.Errorf("DiskEvaluationKeySet: load GaloisKey[%d]: %w", galEl, err)
	}

	return gk, nil
}

// GetGaloisKeysList returns the list of all Galois elements for which
// keys exist on disk. This does NOT load any keys — it only returns
// the known element list from the index.
//
// This is called by rlwe.NewEvaluator and rlwe.Evaluator.WithKey to
// precompute automorphism NTT indices. It is safe and efficient because
// it requires no disk I/O.
func (d *DiskEvaluationKeySet) GetGaloisKeysList() []uint64 {
	return d.galoisElsList
}

// GetRelinearizationKey retrieves the RelinearizationKey.
// If already loaded by the prefetcher, returns immediately.
// Otherwise, loads synchronously from disk.
func (d *DiskEvaluationKeySet) GetRelinearizationKey() (*rlwe.RelinearizationKey, error) {
	// Try prefetcher first
	if rlk := d.prefetcher.GetRelinearizationKey(); rlk != nil {
		return rlk, nil
	}

	// Fallback: synchronous load
	if d.index.RelinKeyPath == "" {
		return nil, fmt.Errorf("RelinearizationKey not found in index")
	}

	rlk, err := LoadRelinearizationKey(d.index.RelinKeyPath)
	if err != nil {
		return nil, fmt.Errorf("DiskEvaluationKeySet: load RelinearizationKey: %w", err)
	}

	return rlk, nil
}

// Reset resets the step counter, allowing the key set to be reused
// for another inference run with the same plan.
func (d *DiskEvaluationKeySet) Reset() {
	d.mu.Lock()
	d.step = 0
	d.mu.Unlock()
}

// Stop waits for all in-flight prefetch operations to complete.
func (d *DiskEvaluationKeySet) Stop() {
	d.prefetcher.Stop()
}

// MemStats returns the number of GaloisKeys currently loaded in memory.
func (d *DiskEvaluationKeySet) MemStats() (galoisKeysLoaded int, relinKeyLoaded bool) {
	d.prefetcher.loadedMu.RLock()
	defer d.prefetcher.loadedMu.RUnlock()

	galoisKeysLoaded = len(d.prefetcher.loadedGK)
	relinKeyLoaded = d.prefetcher.loadedRLK != nil
	return
}
